import { NextRequest, NextResponse } from 'next/server';
import { requireOperator } from '@/lib/auth';
import { query, queryOne } from '@/lib/db';

/**
 * Operator-triggered invoice generation. Creates a draft invoice for the current month
 * for a specific tenant. Useful for testing or catching up missed billing days.
 */
export async function POST(req: NextRequest) {
  await requireOperator();
  const { tenant_id } = await req.json();

  if (!tenant_id) {
    return NextResponse.json({ error: 'tenant_id required' }, { status: 400 });
  }

  const tenant = await queryOne<{
    id: string;
    name: string;
    monthly_fee: string | null;
    billing_currency: string;
    billing_start_date: string | null;
    billing_duration_months: number | null;
  }>(
    `SELECT id, name, monthly_fee, billing_currency, billing_start_date, billing_duration_months FROM tenants WHERE id = $1`,
    [tenant_id]
  );

  if (!tenant) return NextResponse.json({ error: 'Tenant not found' }, { status: 404 });
  if (!tenant.monthly_fee || parseFloat(tenant.monthly_fee) <= 0) {
    return NextResponse.json({ error: 'Tenant has no monthly_fee set. Configure billing in Settings first.' }, { status: 400 });
  }

  // Check expiry using Postgres interval (avoids JS setMonth() edge cases)
  if (tenant.billing_start_date && tenant.billing_duration_months) {
    const expCheck = await queryOne<{ is_expired: boolean }>(
      `SELECT (($1::date::timestamp + ($2 || ' months')::interval) < now()) AS is_expired`,
      [tenant.billing_start_date, tenant.billing_duration_months]
    );
    if (expCheck?.is_expired) {
      return NextResponse.json({ error: 'Subscription has expired. Renew first.' }, { status: 400 });
    }
  }

  const today = new Date();
  const year = today.getFullYear();
  const periodStart = new Date(year, today.getMonth(), 1);
  const periodEnd = new Date(year, today.getMonth() + 1, 0);
  const periodStartStr = periodStart.toISOString().split('T')[0];
  const periodEndStr = periodEnd.toISOString().split('T')[0];

  const existing = await queryOne(
    `SELECT id, invoice_number FROM invoices WHERE tenant_id = $1 AND period_start = $2 AND period_end = $3 LIMIT 1`,
    [tenant_id, periodStartStr, periodEndStr]
  );
  if (existing) {
    return NextResponse.json(
      { error: 'Invoice for this period already exists', invoice: existing },
      { status: 409 }
    );
  }

  const seq = await queryOne<{ nextval: string }>(`SELECT nextval('invoice_number_seq') AS nextval`);
  const num = parseInt(seq?.nextval || '1', 10);
  const invoiceNumber = `MK-${year}-${String(num).padStart(4, '0')}`;

  const monthLabel = periodStart.toLocaleString('en-US', { month: 'long', year: 'numeric' });
  const fee = parseFloat(tenant.monthly_fee);
  const items = [{ description: `Monthly subscription — ${monthLabel}`, amount: fee }];
  const dueDate = new Date(today);
  dueDate.setDate(dueDate.getDate() + 14);

  const created = await queryOne<{ id: string; invoice_number: string }>(
    `INSERT INTO invoices (tenant_id, invoice_number, period_start, period_end, items, total_amount, currency, due_date, notes, status)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'draft')
     RETURNING id, invoice_number`,
    [
      tenant_id,
      invoiceNumber,
      periodStartStr,
      periodEndStr,
      JSON.stringify(items),
      fee,
      tenant.billing_currency || 'GEL',
      dueDate.toISOString().split('T')[0],
      'Manually generated by operator',
    ]
  );

  return NextResponse.json({ ok: true, invoice: created });
}
